[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.build]
cmds = ['npm ci', 'npm run build']

[phases.start]
cmd = 'vite preview --host 0.0.0.0 --port ${PORT:-5173}'

[variables]
NODE_ENV = 'production'