[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[phases.start]
cmd = 'node server.cjs'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'